version: "3.3"
services:
  web:
    image: tar1kan/wiki-api
    environment:
      ASPNETCORE_ENVIRONMENT: "DockerComposeDevelopment"
    ports:
      - "5000:80"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
volumes:
  logvolume01: {}