services:
  web:
    build:
      context: .
      dockerfile: src/LightWiki.Wiki.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "DockerCompose"
    ports:
      - "5000:80"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - postgres
      - mongo
    depends_on:
      - mongo
      - postgres


  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: 1111

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
volumes:
  logvolume01: {}